// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: meter/billingcycles.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Billingcycles struct {
	CycleID  uint64 `protobuf:"varint,1,opt,name=cycleID,proto3" json:"cycleID,omitempty"`
	Start    uint64 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End      uint64 `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	Whin     uint64 `protobuf:"varint,4,opt,name=whin,proto3" json:"whin,omitempty"`
	Whout    uint64 `protobuf:"varint,5,opt,name=whout,proto3" json:"whout,omitempty"`
	Moneyin  uint64 `protobuf:"varint,6,opt,name=moneyin,proto3" json:"moneyin,omitempty"`
	Moneyout uint64 `protobuf:"varint,7,opt,name=moneyout,proto3" json:"moneyout,omitempty"`
	Curency  string `protobuf:"bytes,8,opt,name=curency,proto3" json:"curency,omitempty"`
	Creator  string `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Billingcycles) Reset()         { *m = Billingcycles{} }
func (m *Billingcycles) String() string { return proto.CompactTextString(m) }
func (*Billingcycles) ProtoMessage()    {}
func (*Billingcycles) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1c9cf22c1f8b84, []int{0}
}
func (m *Billingcycles) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Billingcycles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Billingcycles.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Billingcycles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Billingcycles.Merge(m, src)
}
func (m *Billingcycles) XXX_Size() int {
	return m.Size()
}
func (m *Billingcycles) XXX_DiscardUnknown() {
	xxx_messageInfo_Billingcycles.DiscardUnknown(m)
}

var xxx_messageInfo_Billingcycles proto.InternalMessageInfo

func (m *Billingcycles) GetCycleID() uint64 {
	if m != nil {
		return m.CycleID
	}
	return 0
}

func (m *Billingcycles) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Billingcycles) GetEnd() uint64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *Billingcycles) GetWhin() uint64 {
	if m != nil {
		return m.Whin
	}
	return 0
}

func (m *Billingcycles) GetWhout() uint64 {
	if m != nil {
		return m.Whout
	}
	return 0
}

func (m *Billingcycles) GetMoneyin() uint64 {
	if m != nil {
		return m.Moneyin
	}
	return 0
}

func (m *Billingcycles) GetMoneyout() uint64 {
	if m != nil {
		return m.Moneyout
	}
	return 0
}

func (m *Billingcycles) GetCurency() string {
	if m != nil {
		return m.Curency
	}
	return ""
}

func (m *Billingcycles) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Billingcycles)(nil), "electra.meter.Billingcycles")
}

func init() { proto.RegisterFile("meter/billingcycles.proto", fileDescriptor_bf1c9cf22c1f8b84) }

var fileDescriptor_bf1c9cf22c1f8b84 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x63, 0x9a, 0xfe, 0x59, 0xaa, 0x84, 0x2c, 0x90, 0x2e, 0x0c, 0x56, 0xc5, 0xd4, 0xa9,
	0x19, 0x78, 0x83, 0x8a, 0x85, 0xb5, 0x23, 0x5b, 0x1a, 0xae, 0x68, 0x24, 0xd7, 0xae, 0x9c, 0x5b,
	0x15, 0xbf, 0x05, 0x8f, 0xc5, 0xd8, 0x91, 0x11, 0x25, 0xe2, 0x3d, 0x90, 0xaf, 0x13, 0xc4, 0x76,
	0xbe, 0x73, 0x7c, 0x74, 0xad, 0x23, 0xef, 0x0e, 0x48, 0xe8, 0x8b, 0x5d, 0x6d, 0x4c, 0x6d, 0xdf,
	0xaa, 0x50, 0x19, 0x6c, 0xd6, 0x47, 0xef, 0xc8, 0xa9, 0x05, 0x1a, 0xac, 0xc8, 0x97, 0x6b, 0x7e,
	0xf2, 0xf0, 0x23, 0xe4, 0x62, 0xf3, 0xff, 0x99, 0x02, 0x39, 0x65, 0xf5, 0xfc, 0x04, 0x62, 0x29,
	0x56, 0xf9, 0x76, 0x40, 0x75, 0x23, 0xc7, 0x0d, 0x95, 0x9e, 0xe0, 0x8a, 0xfd, 0x04, 0xea, 0x5a,
	0x8e, 0xd0, 0xbe, 0xc2, 0x88, 0xbd, 0x28, 0x95, 0x92, 0xf9, 0x79, 0x5f, 0x5b, 0xc8, 0xd9, 0x62,
	0x1d, 0xbb, 0xe7, 0xbd, 0x3b, 0x11, 0x8c, 0x53, 0x97, 0x21, 0xde, 0x3a, 0x38, 0x8b, 0xa1, 0xb6,
	0x30, 0x49, 0xb7, 0x7a, 0x54, 0xf7, 0x72, 0xc6, 0x32, 0x56, 0xa6, 0x1c, 0xfd, 0x31, 0xff, 0xf0,
	0xe4, 0xd1, 0x56, 0x01, 0x66, 0x4b, 0xb1, 0x9a, 0x6f, 0x07, 0xe4, 0xc4, 0x63, 0x49, 0xce, 0xc3,
	0xbc, 0x4f, 0x12, 0x6e, 0x8a, 0xcf, 0x56, 0x8b, 0x4b, 0xab, 0xc5, 0x77, 0xab, 0xc5, 0x47, 0xa7,
	0xb3, 0x4b, 0xa7, 0xb3, 0xaf, 0x4e, 0x67, 0x2f, 0xb7, 0xfd, 0x20, 0xc5, 0x7b, 0x91, 0x56, 0xa3,
	0x70, 0xc4, 0x66, 0x37, 0xe1, 0xb9, 0x1e, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x15, 0xb9,
	0x93, 0x4b, 0x01, 0x00, 0x00,
}

func (m *Billingcycles) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Billingcycles) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Billingcycles) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintBillingcycles(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Curency) > 0 {
		i -= len(m.Curency)
		copy(dAtA[i:], m.Curency)
		i = encodeVarintBillingcycles(dAtA, i, uint64(len(m.Curency)))
		i--
		dAtA[i] = 0x42
	}
	if m.Moneyout != 0 {
		i = encodeVarintBillingcycles(dAtA, i, uint64(m.Moneyout))
		i--
		dAtA[i] = 0x38
	}
	if m.Moneyin != 0 {
		i = encodeVarintBillingcycles(dAtA, i, uint64(m.Moneyin))
		i--
		dAtA[i] = 0x30
	}
	if m.Whout != 0 {
		i = encodeVarintBillingcycles(dAtA, i, uint64(m.Whout))
		i--
		dAtA[i] = 0x28
	}
	if m.Whin != 0 {
		i = encodeVarintBillingcycles(dAtA, i, uint64(m.Whin))
		i--
		dAtA[i] = 0x20
	}
	if m.End != 0 {
		i = encodeVarintBillingcycles(dAtA, i, uint64(m.End))
		i--
		dAtA[i] = 0x18
	}
	if m.Start != 0 {
		i = encodeVarintBillingcycles(dAtA, i, uint64(m.Start))
		i--
		dAtA[i] = 0x10
	}
	if m.CycleID != 0 {
		i = encodeVarintBillingcycles(dAtA, i, uint64(m.CycleID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBillingcycles(dAtA []byte, offset int, v uint64) int {
	offset -= sovBillingcycles(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Billingcycles) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CycleID != 0 {
		n += 1 + sovBillingcycles(uint64(m.CycleID))
	}
	if m.Start != 0 {
		n += 1 + sovBillingcycles(uint64(m.Start))
	}
	if m.End != 0 {
		n += 1 + sovBillingcycles(uint64(m.End))
	}
	if m.Whin != 0 {
		n += 1 + sovBillingcycles(uint64(m.Whin))
	}
	if m.Whout != 0 {
		n += 1 + sovBillingcycles(uint64(m.Whout))
	}
	if m.Moneyin != 0 {
		n += 1 + sovBillingcycles(uint64(m.Moneyin))
	}
	if m.Moneyout != 0 {
		n += 1 + sovBillingcycles(uint64(m.Moneyout))
	}
	l = len(m.Curency)
	if l > 0 {
		n += 1 + l + sovBillingcycles(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovBillingcycles(uint64(l))
	}
	return n
}

func sovBillingcycles(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBillingcycles(x uint64) (n int) {
	return sovBillingcycles(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Billingcycles) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBillingcycles
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Billingcycles: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Billingcycles: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CycleID", wireType)
			}
			m.CycleID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBillingcycles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CycleID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
			}
			m.Start = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBillingcycles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Start |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field End", wireType)
			}
			m.End = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBillingcycles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.End |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Whin", wireType)
			}
			m.Whin = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBillingcycles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Whin |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Whout", wireType)
			}
			m.Whout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBillingcycles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Whout |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Moneyin", wireType)
			}
			m.Moneyin = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBillingcycles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Moneyin |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Moneyout", wireType)
			}
			m.Moneyout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBillingcycles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Moneyout |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Curency", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBillingcycles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBillingcycles
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBillingcycles
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Curency = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBillingcycles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBillingcycles
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBillingcycles
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBillingcycles(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBillingcycles
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBillingcycles(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBillingcycles
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBillingcycles
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBillingcycles
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBillingcycles
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBillingcycles
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBillingcycles
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBillingcycles        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBillingcycles          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBillingcycles = fmt.Errorf("proto: unexpected end of group")
)
